# Generated by Django 5.2 on 2025-06-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_questionanswer_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bot_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
