# Generated by Django 5.2.4 on 2025-12-18 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_project_title_project_name_alter_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allowed_intents',
            field=models.JSONField(blank=True, default=list, help_text='List of enabled intents for this project. If empty or not set, all intents are treated as allowed.'),
        ),
        migrations.AddField(
            model_name='project',
            name='voice_enabled',
            field=models.BooleanField(default=False, help_text='Enable optional voice (speech input and spoken responses) for this project.'),
        ),
        migrations.AddField(
            model_name='project',
            name='workflow_config',
            field=models.JSONField(blank=True, default=dict, help_text='Optional workflow configuration for advanced agent behavior.'),
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='home.project')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='home.project')),
            ],
        ),
    ]
