# Generated by Django 5.2.4 on 2025-12-18 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_botresponse_feedback_conversationcontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='bot_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='home.botresponse'),
        ),
    ]
